OWNER_NAME="𝗿𝘂𝘀𝗵"
PREFIX="."
PUBLIC_MODE='yes'
AUTO_READ_STATUS="yes"
AUTO_DOWNLOAD_STATUS="no"
BOT_NAME= "𝗥𝗨𝗦𝗛-𝗫𝗩1𝙈𝘿"
IMAGE_MENU= "https://telegra.ph/file/294a9a84cb8f88a07a02f.jpg"
NUMERO_OWNER= ""
OWNER_NAME= "᚛rush᚜"
DATABASE_URL= ""
WARN_COUNT= ""
OPENAI_API_KEY= ""
STARTING_BOT_MESSAGE='yes'
ANTI_DELETE_MESSAGE='yes'

